/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test

     void GSONTest() {

        Path path = Paths.get("C:\\Users\\STUDENT\\codefellows\\401java\\quotes\\app\\src\\main\\resources\\recentquotes.json");
        List<Quote> quotes= App.quoteCollector(path);
        assertEquals(quotes.size() ,App.quoteCollector(path).size());

    }
}
