/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import java.io.*;
import java.lang.reflect.Type;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;

public class App {


    public static void main(String[] args) {
//        Path path = Paths.get("app/src/main/resources/recentquotes.json");
//        List<Quote> quotes = quoteCollector(path);
//        System.out.println(randomQuote(quotes));

        String url = "http://api.forismatic.com/api/1.0/?method=getQuote&format=json&lang=en";
        try {
            HttpURLConnection connection = (HttpURLConnection) new URL(url).openConnection();
            connection.setConnectTimeout(5000);
            connection.setReadTimeout(5000);
            int responseCode = connection.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK) {
                System.out.println(connection);

                InputStreamReader inputStreamReader = new InputStreamReader(connection.getInputStream());
                BufferedReader bufferedReader = new BufferedReader(inputStreamReader);

                // this data is the JSON
                String data = bufferedReader.readLine();
//                System.out.println(data);

                bufferedReader.close();

                Gson gson = new Gson();
                ApiQuote apiQuote = gson.fromJson(data, ApiQuote.class);
                System.out.println(apiQuote);

                BufferedWriter writer = new BufferedWriter(new FileWriter("app/src/main/resources/ApiQuotes.json"));
                gson.toJson(apiQuote, writer);
                writer.close();

            } else {
                System.out.println("server error");
        Path path = Paths.get("app/src/main/resources/recentquotes.json");
        List<Quote> quotes = quoteCollector(path);
        System.out.println(randomQuote(quotes));
            }
        } catch (IOException e) {
            e.printStackTrace();
        }

    }




    public static Quote randomQuote(List<Quote> quotes){
        Random random = new Random();
        int randomIndex = random.nextInt(quotes.size()+1);
        return quotes.get(randomIndex);
    }

    public static List<Quote> quoteCollector(Path path) {
        List<Quote> quotes = null;
        final Type REVIEW_TYPE = new TypeToken<List<Quote>>() {
        }.getType();
        try (
                BufferedReader bufferedReader = Files.newBufferedReader(path);
        ) {

            GsonBuilder gsonBuilder = new GsonBuilder();
            Gson gson = gsonBuilder.create();
            quotes = gson.fromJson(bufferedReader, REVIEW_TYPE);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return quotes;
    }



}
