/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;

import java.io.BufferedReader;
import java.io.IOException;
import java.lang.reflect.Type;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;

public class App {


    public static void main(String[] args) {
        Path path = Paths.get("app/src/main/resources/recentquotes.json");
        List<Quote> quotes = quoteCollector(path);
        System.out.println(randomQuote(quotes));
    }

    public static Quote randomQuote(List<Quote> quotes){
        Random random = new Random();
        int randomIndex = random.nextInt(quotes.size()+1);
        return quotes.get(randomIndex);
    }

    public static List<Quote> quoteCollector(Path path) {
        List<Quote> quotes = null;
        final Type REVIEW_TYPE = new TypeToken<List<Quote>>() {
        }.getType();
        try (
                BufferedReader bufferedReader = Files.newBufferedReader(path);
        ) {

            GsonBuilder gsonBuilder = new GsonBuilder();
            Gson gson = gsonBuilder.create();
            quotes = gson.fromJson(bufferedReader, REVIEW_TYPE);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return quotes;
    }

}
